---
# This playbook contains common plays that will be run on all nodes.
- name: set timezone
  command: /usr/bin/timedatectl set-timezone Europe/Berlin
  command: /usr/bin/timedatectl set-ntp true
  tags: time

- name : update the system
  # Run the equivalent of "pacman -Syu" as a separate step
  pacman: update_cache=yes upgrade=yes
  tags: pacman

- name: install zsh
  pacman: name=zsh state=latest update_cache=yes
  tags: pacman

- name: install git
  pacman: name=git state=latest update_cache=yes
  tags: pacman

- name: install cmake
  pacman: name=cmake state=latest update_cache=yes
  tags: pacman

- name: install basic editing tools
  pacman: name={{item}} state=latest update_cache=yes
  with_items:
      - vim
      - ranger
      - tmux
  tags: pacman

- include: user.yml tags=users
- include: rust.yml tags=languages
- include: elixir.yml tags=languages
- include: clojure.yml tags=languages
- include: dotfiles.yml

# When all is set and done
- name: Force flori to change password
  shell: chage -d 0 flori
  when: flori.changed
