---

- name: install rust and cargo
  pacman: name={{item}} state=latest update_cache=yes
  with_items:
      - rust
      - cargo
  tags: pacman

- name: install cargo-watch
  become: yes
  become_user: flori
  command: cargo install cargo-watch
  args:
      creates: /home/flori/.cargo/bin/cargo-watch
