---

- name: Delete default user from Vagrant box
  user: name=terry state=absent remove=yes

- name: Make sure we have a 'admin' group
  group:
    name: admin
    state: present

- name: Allow 'wheel' group to have sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    #line: '%wheel      ALL=(ALL) NOPASSWD:ALL'
    line: '%admin      ALL=(ALL:ALL) ALL'

- name: Setup user flori
  user:
      name: flori
      password: "{{ 'password' | password_hash('sha512') }}"
      comment: "Florian Fischer"
      shell: /bin/zsh
      uid: 1000
      groups: admin
      #append: yes
      state: present
      update_password: on_create
  register: flori
  tags: user

- name: Add public key
  authorized_key:
    user: flori
    key: "{{ lookup('file', 'id_ed25519.pub') }}"
